services:
  web:
    build: .
    container_name: gamepicker-web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    platform: linux/arm64

  db:
    image: mysql/mysql-server:8.0
    container_name: gamepicker-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gamepicker
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    platform: linux/arm64

  phpmyadmin:
    image: arm64v8/phpmyadmin
    container_name: gamepicker-pma
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    platform: linux/arm64

volumes:
  dbdata:
